serverUrl: tcp://192.168.1.142:1883
username: relay
password: relay
clientId: aggregator
aggregations:
  - type: NAND
    in:
      - thermostat/HyruleCastle
      - thermostat/DiningRoom
      - thermostat/Study
      - thermostat/LivingRoom
      - thermostat/Girls
      - thermostat/MasterBedroom
    out: heating/wall/set
  - type: NAND
    in:
      - thermostat/Kitchen
      - thermostat/Toilet
      - thermostat/KidsBathroom
      - thermostat/MasterBathroom
      - thermostat/Hallway
    out: heating/floor/set